In [1]:
#numpy araay manipulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[6, 7, 1, 2],
       [8, 2, 7, 2],
       [6, 5, 3, 8]])

In [5]:
arr.reshape(6,2)

array([[6, 7],
       [1, 2],
       [8, 2],
       [7, 2],
       [6, 5],
       [3, 8]])

In [6]:
arr.reshape(2,6)

array([[6, 7, 1, 2, 8, 2],
       [7, 2, 6, 5, 3, 8]])

In [7]:
arr.T

array([[6, 8, 6],
       [7, 2, 5],
       [1, 7, 3],
       [2, 2, 8]])

In [8]:
arr.flatten()

array([6, 7, 1, 2, 8, 2, 7, 2, 6, 5, 3, 8])

In [9]:
arr1 = np.array([1,2,3,4,5])

In [10]:
arr1

array([1, 2, 3, 4, 5])

In [11]:
arr1.ndim

1

In [12]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [13]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

In [14]:
arr

array([[6, 7, 1, 2],
       [8, 2, 7, 2],
       [6, 5, 3, 8]])

In [15]:
np.squeeze(arr)

array([[6, 7, 1, 2],
       [8, 2, 7, 2],
       [6, 5, 3, 8]])

In [16]:
data = np.array([[1],[2],[3]])

In [17]:
data

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(data)

array([1, 2, 3])

In [19]:
arr1

array([1, 2, 3, 4, 5])

In [20]:
np.repeat(arr,3)

array([6, 6, 6, 7, 7, 7, 1, 1, 1, 2, 2, 2, 8, 8, 8, 2, 2, 2, 7, 7, 7, 2,
       2, 2, 6, 6, 6, 5, 5, 5, 3, 3, 3, 8, 8, 8])

In [21]:
np.roll(arr1,shift=2)

array([4, 5, 1, 2, 3])

In [22]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [45]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(10,20,(3,4))

In [46]:
arr2

array([[12, 17, 11, 13],
       [17, 19, 15, 19],
       [10, 12, 11, 16]])

In [47]:
arr1

array([[1, 4, 9, 8],
       [6, 6, 4, 8],
       [4, 8, 3, 9]])

In [48]:
arr1+arr2

array([[13, 21, 20, 21],
       [23, 25, 19, 27],
       [14, 20, 14, 25]])

In [49]:
arr1*arr2

array([[ 12,  68,  99, 104],
       [102, 114,  60, 152],
       [ 40,  96,  33, 144]])

In [50]:
arr1-arr2

array([[-11, -13,  -2,  -5],
       [-11, -13, -11, -11],
       [ -6,  -4,  -8,  -7]])

In [51]:
arr1/arr2

array([[0.08333333, 0.23529412, 0.81818182, 0.61538462],
       [0.35294118, 0.31578947, 0.26666667, 0.42105263],
       [0.4       , 0.66666667, 0.27272727, 0.5625    ]])

In [52]:
arr1%arr2

array([[1, 4, 9, 8],
       [6, 6, 4, 8],
       [4, 8, 3, 9]])

In [53]:
arr1 & arr2

array([[0, 0, 9, 8],
       [0, 2, 4, 0],
       [0, 8, 3, 0]])

In [54]:
~arr1

array([[ -2,  -5, -10,  -9],
       [ -7,  -7,  -5,  -9],
       [ -5,  -9,  -4, -10]])

In [55]:
arr1|arr2

array([[13, 21, 11, 13],
       [23, 23, 15, 27],
       [14, 12, 11, 25]])

In [56]:
arr1==arr2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [57]:
# numpy string functions

In [61]:
arr = np.array(['Neeraj', 'Prasad'])

In [62]:
arr

array(['Neeraj', 'Prasad'], dtype='<U6')

In [64]:
np.char.upper(arr)

array(['NEERAJ', 'PRASAD'], dtype='<U6')

In [65]:
np.char.title(arr)

array(['Neeraj', 'Prasad'], dtype='<U6')

In [66]:
np.char.capitalize(arr)

array(['Neeraj', 'Prasad'], dtype='<U6')

In [67]:
# numpy math functions

In [68]:
arr1

array([[1, 4, 9, 8],
       [6, 6, 4, 8],
       [4, 8, 3, 9]])

In [69]:
np.sin(arr1)

array([[ 0.84147098, -0.7568025 ,  0.41211849,  0.98935825],
       [-0.2794155 , -0.2794155 , -0.7568025 ,  0.98935825],
       [-0.7568025 ,  0.98935825,  0.14112001,  0.41211849]])

In [70]:
np.cos(arr1)

array([[ 0.54030231, -0.65364362, -0.91113026, -0.14550003],
       [ 0.96017029,  0.96017029, -0.65364362, -0.14550003],
       [-0.65364362, -0.14550003, -0.9899925 , -0.91113026]])

In [71]:
np.exp(arr1)

array([[2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 2.98095799e+03],
       [4.03428793e+02, 4.03428793e+02, 5.45981500e+01, 2.98095799e+03],
       [5.45981500e+01, 2.98095799e+03, 2.00855369e+01, 8.10308393e+03]])

In [73]:
np.power(arr1,2)

array([[ 1, 16, 81, 64],
       [36, 36, 16, 64],
       [16, 64,  9, 81]])

In [74]:
np.sqrt(arr1)

array([[1.        , 2.        , 3.        , 2.82842712],
       [2.44948974, 2.44948974, 2.        , 2.82842712],
       [2.        , 2.82842712, 1.73205081, 3.        ]])

In [76]:
np.mean(arr1)

5.833333333333333

In [79]:
np.median(arr1)

6.0