In [1]:
#sort search and counting function

In [2]:
import numpy as np

In [3]:
arr = np.array([4,5,2,7,2,6,9,3,7,3,1,4,7,3,9,4,3,2,75,3,4,6,4,3])

In [4]:
np.sort(arr)

array([ 1,  2,  2,  2,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  5,  6,
        6,  7,  7,  7,  9,  9, 75])

In [5]:
np.searchsorted(arr,12)

18

In [6]:
arr1 = np.array([0,2,5,1,6,9,0,3,4,8,44,9,32,7,8,4,2,5])

In [7]:
np.count_nonzero(arr1)

16

In [8]:
arr

array([ 4,  5,  2,  7,  2,  6,  9,  3,  7,  3,  1,  4,  7,  3,  9,  4,  3,
        2, 75,  3,  4,  6,  4,  3])

In [9]:
np.where(arr>6)

(array([ 3,  6,  8, 12, 14, 18]),)

In [11]:
np.extract(arr>6,arr)

array([ 7,  9,  7,  7,  9, 75])

In [12]:
# numpy byte swaping

In [13]:
arr

array([ 4,  5,  2,  7,  2,  6,  9,  3,  7,  3,  1,  4,  7,  3,  9,  4,  3,
        2, 75,  3,  4,  6,  4,  3])

In [14]:
arr.byteswap()

array([ 288230376151711744,  360287970189639680,  144115188075855872,
        504403158265495552,  144115188075855872,  432345564227567616,
        648518346341351424,  216172782113783808,  504403158265495552,
        216172782113783808,   72057594037927936,  288230376151711744,
        504403158265495552,  216172782113783808,  648518346341351424,
        288230376151711744,  216172782113783808,  144115188075855872,
       5404319552844595200,  216172782113783808,  288230376151711744,
        432345564227567616,  288230376151711744,  216172782113783808])

In [15]:
#numpu copy and viwes

In [16]:
arr

array([ 4,  5,  2,  7,  2,  6,  9,  3,  7,  3,  1,  4,  7,  3,  9,  4,  3,
        2, 75,  3,  4,  6,  4,  3])

In [17]:
a = np.copy(arr)

In [18]:
a

array([ 4,  5,  2,  7,  2,  6,  9,  3,  7,  3,  1,  4,  7,  3,  9,  4,  3,
        2, 75,  3,  4,  6,  4,  3])

In [19]:
b= arr.view()

In [20]:
b

array([ 4,  5,  2,  7,  2,  6,  9,  3,  7,  3,  1,  4,  7,  3,  9,  4,  3,
        2, 75,  3,  4,  6,  4,  3])

In [22]:
b[0] = 67

In [23]:
b

array([67,  5,  2,  7,  2,  6,  9,  3,  7,  3,  1,  4,  7,  3,  9,  4,  3,
        2, 75,  3,  4,  6,  4,  3])

In [24]:
arr

array([67,  5,  2,  7,  2,  6,  9,  3,  7,  3,  1,  4,  7,  3,  9,  4,  3,
        2, 75,  3,  4,  6,  4,  3])

In [25]:
#numpy matrix

In [26]:
import numpy.matlib as nm

In [27]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [28]:
nm.ones((6,7))

matrix([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [29]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [30]:
# numpy linerar algebra


In [31]:
arr1 = np.random.randint([[2,3],[4,5]])
arr2 = np.random.randint([[5,3],[2,5]])

In [32]:
arr1

array([[1, 1],
       [1, 1]])

In [33]:
arr2

array([[1, 1],
       [0, 4]])

In [34]:
np.dot(arr1,arr2)

array([[1, 5],
       [1, 5]])

In [35]:
arr1@arr2

array([[1, 5],
       [1, 5]])