In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)

In [4]:
type(ar)

numpy.ndarray

In [5]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
np.asarray(l)

array([1, 2, 3, 4])

In [7]:
a =[3,2,4,]

In [8]:
np.array(a)

array([3, 2, 4])

In [9]:
b = np.matrix(l)

In [10]:
b

matrix([[1, 2, 3, 4]])

In [11]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [12]:
a= np.array(l)

In [13]:
c = a

In [14]:
c

array([1, 2, 3, 4])

In [15]:
a

array([1, 2, 3, 4])

In [16]:
c[0] = 100

In [17]:
c

array([100,   2,   3,   4])

In [18]:
a

array([100,   2,   3,   4])

In [19]:
d = np.copy(a)

In [20]:
d

array([100,   2,   3,   4])

In [21]:
a

array([100,   2,   3,   4])

In [22]:
a[1] = 400

In [23]:
a

array([100, 400,   3,   4])

In [24]:
d

array([100,   2,   3,   4])

In [25]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [27]:
itrable = (i*i for i in range(5))

In [28]:
np.fromiter(itrable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [29]:
np.fromstring("234 789",sep = " ")

array([234., 789.])

In [30]:
np.fromstring("234,789",sep = ",")

array([234., 789.])

In [31]:
# numpy - datatypes

In [32]:
l = [1,2,3,4,5]

In [33]:
ar = np.array(l)

In [34]:
ar

array([1, 2, 3, 4, 5])

In [35]:
ar.ndim

1

In [36]:
ar2 = np.array([[1,2,3,4,5],[5,6,7,8,4]])

In [37]:
ar2.ndim

2

In [38]:
ar.size

5

In [39]:
ar2.size

10

In [40]:
ar2

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 4]])

In [41]:
ar2.shape

(2, 5)

In [42]:
ar.dtype

dtype('int64')

In [44]:
ar22 = np.array([[(1.4,45,23), (23,75.8,45)]])

In [45]:
ar22

array([[[ 1.4, 45. , 23. ],
        [23. , 75.8, 45. ]]])

In [46]:
ar.dtype

dtype('int64')

In [47]:
ar22.dtype

dtype('float64')

In [49]:
list(range(5))

[0, 1, 2, 3, 4]

In [50]:
list(range(3.5,9))

TypeError: 'float' object cannot be interpreted as an integer

In [51]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [52]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [53]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [54]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [55]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [59]:
arr4 = np.zeros((3,4,5,6))

In [61]:
arr4

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
        

In [63]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [65]:
on = np.ones((2,3,2))

In [66]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [67]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [70]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [71]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [72]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [73]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [75]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [78]:
np.random.randn(3,4)

array([[-0.70441556, -0.07496039, -0.59553227,  1.10823821],
       [ 0.88671335,  2.5114801 , -0.77110894,  0.76184953],
       [ 0.08305324,  0.51420138,  0.40473356,  0.52221923]])

In [79]:
d = np.random.randn(3,4)

In [81]:
import pandas as pd

In [82]:
df  = pd.DataFrame(d)

In [83]:
df

0         1         2         3
0  0.327423  1.614398  2.347618  1.442839
1 -0.039223 -0.036581  0.995107 -1.363733
2  0.158906 -0.003531 -1.316912 -1.781566

In [84]:
d = np.random.rand(3,4)

In [85]:
d

array([[0.23417589, 0.45739574, 0.41384071, 0.73416668],
       [0.73863687, 0.11861592, 0.6524579 , 0.87066805],
       [0.36322698, 0.04494415, 0.60919348, 0.58254018]])

In [86]:
np.random.randint(1,110, (3,4))

array([[ 92,  26,  60,  47],
       [ 94,  58,  17,  78],
       [103,  17,  92,  53]])

In [87]:
d

array([[0.23417589, 0.45739574, 0.41384071, 0.73416668],
       [0.73863687, 0.11861592, 0.6524579 , 0.87066805],
       [0.36322698, 0.04494415, 0.60919348, 0.58254018]])

In [88]:
arr = d

In [89]:
arr

array([[0.23417589, 0.45739574, 0.41384071, 0.73416668],
       [0.73863687, 0.11861592, 0.6524579 , 0.87066805],
       [0.36322698, 0.04494415, 0.60919348, 0.58254018]])

In [92]:
arr1 = arr.reshape(6,2)

In [93]:
arr1

array([[0.23417589, 0.45739574],
       [0.41384071, 0.73416668],
       [0.73863687, 0.11861592],
       [0.6524579 , 0.87066805],
       [0.36322698, 0.04494415],
       [0.60919348, 0.58254018]])

In [94]:
arr1[1,1]

0.7341666795750464

In [96]:
arr1[2:5,1]

array([0.11861592, 0.87066805, 0.04494415])

In [98]:
arr =np.random.randint(1,100,(5,5))

In [99]:
arr

array([[17,  2, 57, 80, 43],
       [66, 26,  3, 26, 30],
       [45, 78, 90, 14, 90],
       [56, 84, 58, 56, 31],
       [18, 47, 64, 24, 37]])

In [100]:
arr>50

array([[False, False,  True,  True, False],
       [ True, False, False, False, False],
       [False,  True,  True, False,  True],
       [ True,  True,  True,  True, False],
       [False, False,  True, False, False]])

In [101]:
arr[arr>50]

array([57, 80, 66, 78, 90, 90, 56, 84, 58, 56, 64])

In [102]:
arr

array([[17,  2, 57, 80, 43],
       [66, 26,  3, 26, 30],
       [45, 78, 90, 14, 90],
       [56, 84, 58, 56, 31],
       [18, 47, 64, 24, 37]])

In [103]:
arr[2:4,[1,2]]

array([[78, 90],
       [84, 58]])

In [106]:
arr[0][0] = 34

In [107]:
arr

array([[34,  2, 57, 80, 43],
       [66, 26,  3, 26, 30],
       [45, 78, 90, 14, 90],
       [56, 84, 58, 56, 31],
       [18, 47, 64, 24, 37]])

In [108]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [109]:
arr1

array([[2, 2, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [110]:
arr2

array([[2, 2, 1],
       [2, 2, 1],
       [1, 1, 1]])

In [111]:
arr3 = arr1+arr2

In [112]:
arr3

array([[4, 4, 3],
       [4, 4, 3],
       [2, 2, 3]])

In [113]:
arr1-arr2

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [114]:
arr1/arr2

array([[1., 1., 2.],
       [1., 1., 2.],
       [1., 1., 2.]])

In [115]:
arr1*arr2

array([[4, 4, 2],
       [4, 4, 2],
       [1, 1, 2]])

In [116]:
arr1@arr2

array([[10, 10,  6],
       [10, 10,  6],
       [ 6,  6,  4]])

In [117]:
arr1/0

/tmp/ipykernel_151/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [118]:
arr1*2

array([[4, 4, 4],
       [4, 4, 4],
       [2, 2, 4]])

In [119]:
#numpy Broadcasting

In [120]:
arr = np.zeros((4,4))

In [121]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
row = np.array([1,2,3,4])

In [123]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [124]:
row.T

array([1, 2, 3, 4])

In [125]:
col = np.array([[1,2,3,4]])

In [126]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [127]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [128]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [129]:
arr1 = np.random.randint(1,4, (3,4))

In [130]:
arr1

array([[3, 3, 1, 2],
       [2, 1, 1, 1],
       [3, 1, 2, 2]])

In [131]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.        , 1.        ],
       [1.73205081, 1.        , 1.41421356, 1.41421356]])

In [132]:
np.exp(arr1)

array([[20.08553692, 20.08553692,  2.71828183,  7.3890561 ],
       [ 7.3890561 ,  2.71828183,  2.71828183,  2.71828183],
       [20.08553692,  2.71828183,  7.3890561 ,  7.3890561 ]])